# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#b3e3ca" }

# Hovered
hovered         = { fg = "#1e2528", bg = "#cbe3b3", bold = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#f5d098", bold = true, italic = true, underline = true }
find_position = { fg = "#f3c0e5", bg = "reset", bold = true, italic = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied   = { fg = "#cbe3b3", bg = "#cbe3b3" }
marker_cut      = { fg = "#f57f82", bg = "#f57f82" }
marker_marked   = { fg = "#b3e3ca", bg = "#b3e3ca" }
marker_selected = { fg = "#f5d098", bg = "#f5d098" }

# Count
count_copied   = { fg = "#1e2528", bg = "#cbe3b3" }
count_cut      = { fg = "#1e2528", bg = "#f57f82" }
count_selected = { fg = "#1e2528", bg = "#f5d098" }

# Border
border_symbol = "│"
border_style  = { fg = "#262f33" }

# Highlighting
syntect_theme = ""

# : }}}


# : Tabs {{{

[tabs]
active   = { bg = "#b3e3ca", bold = true }
inactive = { fg = "#b3e3ca", bg = "#262f33" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Mode {{{

[mode]
normal_main = { fg = "#1e2528", bg = "#cbe3b3", bold = true }
normal_alt  = { fg = "#b3e3ca", bg = "#262f33", bold = true }

# Select mode
select_main = { fg = "#1e2528", bg = "#f57f82", bold = true }
select_alt  = { fg = "#b3e3ca", bg = "#262f33", bold = true }

# Unset mode
unset_main = { fg = "#1e2528", bg = "#b3e3ca", bold = true }
unset_alt  = { fg = "#b3e3ca", bg = "#262f33", bold = true }

# : }}}


# : Status bar {{{

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
permissions_s = { fg = "#1e2528" }
permissions_t = { fg = "#cbe3b3" }
permissions_r = { fg = "#f5d098" }
permissions_w = { fg = "#f57f82" }
permissions_x = { fg = "#b3e3ca" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#b3e3ca", bg = "#1e2528" }
progress_error  = { fg = "#f57f82", bg = "#1e2528" }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#1e2528" }
cand            = { fg = "#b3e3ca" }
rest            = { fg = "#1e2528" }
desc            = { fg = "#f3c0e5" }
separator       = "  "
separator_style = { fg = "#1e2528" }

# : }}}


# : Confirmation {{{

[confirm]
border     = { fg = "#b3e3ca" }
title      = { fg = "#b3e3ca" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#b3e3ca" }
title  = { fg = "#b3e3ca" }

# Table
tbl_col  = { fg = "#b3e3ca" }
tbl_cell = { fg = "#f5d098", reversed = true }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#cbe3b3" }
title_warn  = { fg = "#f5d098" }
title_error = { fg = "#f57f82" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : Picker {{{

[pick]
border   = { fg = "#b3e3ca" }
active   = { fg = "#f3c0e5", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#b3e3ca" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border   = { fg = "#b3e3ca" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Task manager {{{

[tasks]
border  = { fg = "#b3e3ca" }
title   = {}
hovered = { fg = "#f3c0e5", underline = true }

# : }}}


# : Help menu {{{

[help]
on      = { fg = "#b3e3ca" }
run     = { fg = "#f3c0e5" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#96b4aa", bg = "#f8f9e8" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#b2caed" },

	# Media
	{ mime = "{audio,video}/*", fg = "#f3c0e5" },

	# Archives
	{ mime = "application/*zip", fg = "#f57f82" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f57f82" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#b3e3ca" },

	# Fallback
	{ name = "*", fg = "#b3e3ca" },
	{ name = "*/", fg = "#b3e3ca" }
]

# : }}}
