[window]
padding = { x = 15, y = 15 }
opacity = 0.85

[font.normal]
# family = "Liga SFMono Nerd Font"
# family = "Google Sans Code NF"
# family = "CommitMonoGoerll"
# family = "SFMono Nerd Font"
family = "PaperMono"
# family = "Martian Mono"
# style = "medium" ->

# Ghostty-based Alacritty Colors
[colors.primary]
background = '#1e2528'
foreground = '#f8f9e8'

[colors.cursor]
cursor = '#cbe3b3'
text = '#171c1f'

[colors.selection]
background = '#374145'
text = '#f8f9e8'

# Normal colors
[colors.normal]
black   = '#1e2528'  # palette 0
red     = '#f57f82'  # palette 1
green   = '#cbe3b3'  # palette 2
yellow  = '#f5d098'  # palette 3
blue    = '#b2caed'  # palette 4
magenta = '#f3c0e5'  # palette 5
cyan    = '#b3e3ca'  # palette 6
white   = '#f8f9e8'  # palette 7

# Bright colors
[colors.bright]
black   = '#262f33'  # palette 8
red     = '#f57f82'  # palette 9
green   = '#cbe3b3'  # palette 10
yellow  = '#f5d098'  # palette 11
blue    = '#b2caed'  # palette 12
magenta = '#f3c0e5'  # palette 13
cyan    = '#b3e3ca'  # palette 14
white   = '#96b4aa'  # palette 15
